version: '3.8'

services:
  breaker-panel-helper:
    # Use pre-built image from GitHub Container Registry
    image: ghcr.io/your-username/breaker-panel-helper:latest
    # Or build locally if you prefer
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: breaker-panel-helper
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Persistent database storage
      - ./data:/app/data
      # Optional: Mount CSV files for import
      - ./csv-imports:/app/csv-imports:ro
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/breaker_panel.db
      - PORT=3000
      # Optional: Set timezone
      - TZ=America/New_York
    labels:
      # Unraid template labels
      - "net.unraid.docker.managed=dockerman"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/database.png"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => { r.statusCode === 200 ? process.exit(0) : process.exit(1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: breaker-panel-network