name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint --if-present

    - name: Run tests
      run: npm test --if-present

    - name: Run feature validation
      run: node validate-features.js

    - name: Check database creation
      run: |
        node -e "
          const sqlite3 = require('sqlite3');
          const db = new sqlite3.Database('test.db');
          console.log('Database creation test passed');
          db.close();
        "

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=high

    - name: Run Snyk security scan
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [test, security]
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        docker run --rm -d --name test-container \
          -p 3000:3000 \
          -e NODE_ENV=production \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
        # Wait for container to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:3000 || exit 1
        
        # Cleanup
        docker stop test-container

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Generate deployment docs
      run: |
        mkdir -p docs
        cp DEPLOYMENT.md docs/
        cp CLAUDE.md docs/
        
        # Create index page
        cat > docs/index.md << 'EOF'
        # Breaker Panel Helper Documentation
        
        ## Quick Links
        - [Deployment Guide](DEPLOYMENT.md)
        - [Architecture & Development](CLAUDE.md)
        
        ## Docker Image
        ```bash
        docker pull ghcr.io/${{ github.repository }}:latest
        ```
        
        ## Latest Release
        ![Docker Image Version](https://ghcr-badge.egpl.dev/${{ github.repository }}/latest_by_date)
        ![Docker Image Size](https://ghcr-badge.egpl.dev/${{ github.repository }}/size)
        EOF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate changelog
      id: changelog
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Generate release notes
        cat > release_notes.md << EOF
        ## Docker Image
        \`\`\`bash
        docker pull ghcr.io/${{ github.repository }}:${VERSION}
        docker pull ghcr.io/${{ github.repository }}:latest
        \`\`\`
        
        ## Deployment
        For Unraid deployment instructions, see the [Deployment Guide](https://github.com/${{ github.repository }}/blob/main/DEPLOYMENT.md).
        
        ## Changes in this release
        - See commit history for detailed changes
        - All tests passing
        - Multi-architecture support (amd64, arm64)
        EOF

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.changelog.outputs.version }}
        body_path: release_notes.md
        draft: false
        prerelease: false

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: [build, create-release]
    if: always() && (needs.build.result == 'success' || needs.create-release.result == 'success')
    
    steps:
    - name: Notify success
      run: |
        echo "✅ CI/CD Pipeline completed successfully!"
        echo "📦 Docker image available at: ghcr.io/${{ github.repository }}"
        
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "🎉 New release created: ${GITHUB_REF#refs/tags/}"
        fi